#+SETUPFILE: ./config/setupfile.org
#+LATEX_HEADER: \newcommand{\newtitle}{\vspace{1.0cm} Visit to Brasilia}
#+LATEX_HEADER: \newcommand{\authorname}{Joao Mauricio Rosal \\ \textit{Chief Economist, PhD} \\Vinicius Alves \\ \it Economist} 

#+BEGIN_EXPORT latex
\thispagestyle{firstpagestyle}
    \begin{tcolorbox}[colbak=red!5!white, colframe=red!0!white]
      \NewsItem{Takeaways:}
        \it{
    \import{latex/}{highlights}}
    \end{tcolorbox}
\vspace{-0.8cm}
#+END_EXPORT

#+include: "./html/salutation.html" export html
#+include: "./html/highlights.html" export html

* Main Points
#+ATTR_LATEX: :environment compactitem :options [$\diamond$]
We met yesterday with some politicians of the highest caliber on the
government's side of the aisle, ranging from the Speaker of the Lower
House, Mr. Rodrigo Maia, and the Temer's Chief of staff, Eliseu
Patilha, to the leader of the Government in the Congress, Senator
Romero Juca. Clearly, one of the best talks Brasilia can offer
these days.

We discussed a multitude of topics concerning the political /cum/
economic agenda. Some highlights looked particularly enticing for us,
as follow:

- *Second Charge Against President Temer*: All our interlocutors
  agreed that its bite has been severely undermined by the recent
  events around Mr. Joesley Batista's plea bargain. This should
  certainly make the process less traumatic and more expedient
  compared to the first charge. In particular, this should lower
  rent-seeking/bargain within the Lower House and thus favoring
  Mr. Temer down the line.

  That said, there were two competing views. On one hand, as confirmed
  by the press this morning, Mr. Rodrigo Maia understands the charge
  should take full priority from here on, both at Constitution and
  Justice Commission (CCJ) and on the floor. According to this logic,
  only after that, the government should be able to assess its real
  support on the Lower House in order to tackle other matters.

  The other competing view, put forth by Mr. Juca, looked more
  sanguine to us. Accordingly, the best strategy at this juncture is
  to let the charge dormant in the House and thus focus on other
  businesses, after it is through the CCJ. After all, time is against
  any reform and since it is down to the opposition to prove Temer's
  guilty, one should just leave them struggling to do anything
  meaningful with this charge, while the government mind its own
  businesses.
  
- *Social Security Reform*. Overall, our interlocutors made it clear
  that, as soon as the political environment allows, the reform ought
  to be pressed on. However, they all agree that the proposal as is
  today lacks the necessary support in the Lower House.

  That said, our impression is that none of them looks willing to
  leave the issue dormant. This is, by doing so, the markets may give
  the government at thumbs down, which could be a real liability for
  them in 2018.

  At moment, the official stance is to stand firm by the report of the
  rapporteur, Mr. Arthur Maia. However, one could spot that in so far
  as some pillars are kept in place, particularly the minimum
  requirement age and a transition rule - including civil servants,
  that would be good enough for them.

  Be all that as it may, it is worth noting that, as one of our interlocutors have stressed,
  high ranked members of the Judiciary are already lobbying in favor
  of excluding civil servants from the reform. Hence, the battle won't
  be any smoother this time around.

- *Fiscal Agenda*. While everybody seemed wary about the fate of the
  social security reform, they looked less so with regard to other
  short-term measures that can safeguard the 2018's primary target. In
  particular, they look confidence on soon-to-be issued provisional
  measures on: 1) postponing civil servants wage bills, 2) increasing
  their pension contributions, and 3) taxing some special funds. At
  the end of the day, these matters demand only single majority in
  both Houses, and they are relative comfortable they can rely on
  that.

  With regards to the Refis, they all agreed the matter is pretty much
  settled and it should be approved within the next week or so. The
  unwinding of the social security tax subsidies (Reoneracao) looked
  more of a complex matter, however, and, possibly, the discussion
  over the topic may have to be re-ignited from scratch with another
  bill sent to Congress.

  In regard to the policy agenda, one of our interlocutors dropped an
  important date for us to monitor: March 2018, when all Ministers
  running for public offices in 2018 will have to step
  down. Therefore, from then on, policies depending on the Congress
  are likely to be only about small bear issues.
  
- *2018 Elections*. Two facts seemed to have increased the confidence
  that a center-right candidacy may arrive in good shape for the
  2018's presidential election. For one, Lula's candidacy looks no
  longer viable to our interlocutors, and, two, the economy is picking
  up, which could gather further momentum if the social security is
  approved.

  In addition, they all shared the idea the Mr. Bolsonaro is going to
  be an important player next year. However, should politicians
  sponsoring the government right now not screw things up along the
  way, they may actually score a victory, spite of Mr. Bolsonaro.

  The Doria /versus/ Ackmin debate is certainly not settled in
  Brasilia. In fact, some of our interlocutors understand that this
  competition may be detrimental to PSDB, to the extent that it may
  open room for other parties to launch their own candidates. Others,
  however, understand that parties within Temer's coalition are likely
  to stand united around a single candidate already from the outset,
  say, by March 2018. In order to do so, however, these grand
  coalition should take whatever candidate is leading the context -
  Mr. Meirelles included - and go for it.


#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT


* Disclaimer
#+BEGIN_EXPORT latex
\smallsize
#+END_EXPORT

#+BEGIN_QUOTE
This report has been produced by Guide Investimentos S.A Corretora de
Valores solely for its recipients and should not be distributed
without previous consent from Guide Investimentos S.A.  Although this
report is based upon the most reliable public information, Guide
Investimentos makes no warranties of the reliability of such
information. This document is for informational purposes only and does
not constitute any tender to sell or buy financial
instruments. Information discussed herein is not suitable for all
investors and it does not aim at providing any trading strategy for
individual goals. Investors should have experience and knowledge of
the risks in FX/Fixed Income markets. Guide Investimentos S.A
Corretora de Valores has no obligation to update, revise or modify any
information contained herein. Guide Investimentos and its analysts
shall not be held responsible for any accidental incorrect
information, nor for investment decisions taken based upon the
information contained herein. Additional information discussed on this
report is available upon request.  Analysts each certify that the
views expressed in this report represent only personal views produced
independently, including with respect Guide Investimentos S.A
Corretora de Valores. This report should not be considered as research
report ("relatório de análise") for the purposes of the article 1 of
CVM Instruction NR 483. Opinions, estimates and projections contained
herein express the current judgment of the analysts build on the date
this report was released and therefore can be changed without
notice. Analysts do not accept any liability that incorrect use of
this report could cause, including financial losses. Upon accepting
this document, one should agree with all the above-mentioned
limitations
#+END_QUOTE


* COMMENT Local Variables
# Local Variables:
# eval: (load-file "./elisp/publishing.el")
# END:
