#+SETUPFILE: ./config/setupfile.org
#+LATEX_HEADER: \newcommand{\newtitle}{\vspace{1.0cm} Bolsonaro \\ More Than Just a Myth}
#+LATEX_HEADER: \newcommand{\authorname}{Joao Mauricio Rosal \\ \textit{Chief Economist, PhD} \\Vinicius Alves \\ \it Economist} 

#+BEGIN_EXPORT latex
\thispagestyle{firstpagestyle}
    \begin{tcolorbox}[colbak=red!5!white, colframe=red!0!white]
      \NewsItem{Takeaways:}
        \it{
    \import{latex/}{highlights}}
    \end{tcolorbox}
\vspace{-0.8cm}
#+END_EXPORT

#+include: "./html/salutation.html" export html
#+include: "./html/highlights.html" export html

* Main Points
#+ATTR_LATEX: :environment compactitem :options [$\diamond$]
*Mr. Bolsonaro is no passing fad*. Mr. Bolsonaro has a well thought
over plan to keep his candidacy competitive throughout the
Presidential context. He is aware he will be subjected to intense
fire, and his weaknesses - as in the case of any other leading
candidate - will be explored by his opponents. Nonetheless, he doesn't
want to be such an easy target and, according to his own words, he is
controlling his exposure to the media and the public at large in order
to safeguard his position on the polls, that he believes is solid.

As an example, during our conversation, he stood up a couple at times
and went to the Lower House' floor in order to vote. He is aware the
press is on him, and he doesn't want to be dubbed shirker in case he
miss a single voting session by accident.

Social media will continue to be a key vehicle to communicate with
sympathizers, who were piling in front of his office at Congress
during our conversation. His temper and debating skills, however,
haven't yet been tested and remain as major question marks ahead of
the presidential context, in our view.

*Mr. Bolsonaro is working to be taken as credibly alternative*. He is
gradually augmenting his exposure to a variety of business groups that
still reckon him as an outsider. This is not only the case of the
financial market's participants, but also of industrial and
agricultural leaderships. In addition, he isn't shying away from
meeting with foreign investors either, but he seems careful enough to
mitigate any risks that such exposure may have on his ratings. In sum,
he plans to ramp up his efforts on this front, but always carefully.

*Mr. Bolsonaro's economic agenda is still taking shape, but signals
indicate it gravitates somewhere on the center-right*. More
concretely, he believes the State ought to be rationalized, with
privatizations included. He also understands that the social security
system calls for some type of reform, albeit through gradual steps in
order to grant its approval by the Congress. He welcomes the discussion over
Central Bank and regulatory agency's independence, but acknowledges he
is unlikely to raise themes such as these during the election process
due to their political sensitivity.

More broadly, he visited may topics without getting necessarily too
deep in many of them. He admits that his ideas are still taking shape,
but acknowledges the need to discuss matters with field specialties in
order to sharpen his thoughts, economics included. In one field,
however, he was more self assured: public safety. He believes it is
due time to amend the legal code in order to improve the rule of law
and individuals rights.

*Mr. Bolsonaro still misses a clear strategy to strike deals with
the political establishment*. He is aware that, should he be elected
the next President he will need a strategy to negotiate policies with
the Congress. In this respect, his always watchful son and Deputy from
Sao Paulo State, Mr. Eduardo Bolsonaro, was quick to say that the next
Congress is more likely to have stronger right-wing leanings, and
should thus be more sympathetic to his father's agenda.

Mr. Bolsonaro himself believes he can speak directly to political
groups - not necessarily political parties, such as the Congress'
religious representatives, and bring them on board. Ourselves, we are
not totally convinced it can work, since bypassing party's leaderships
may be disastrous. Perhaps, this is one of his weakest spot if one
considers what he could deliver, were he chosen the next President of
the country.

*Net/net*. While Mr. Bolsonaro's rhetoric attracts sympathizers
farther to the right, his economic ideas (still taking shape, for
sure) reinforce the thesis that the next Presidential cycle is more
likely to give continuation to a market friendly agenda than
otherwise. Nonetheless, should this really be the case, it remains to
be seen how the next President will strike a deal with the political
establishment in order to push such an agenda forward, once, in one
way or another, he/she should face similar challenges on this front as
President Temer has been facing throughout.




#+BEGIN_EXPORT latex
\newpage
#+END_EXPORT


* Disclaimer
#+BEGIN_EXPORT latex
\smallsize
#+END_EXPORT

#+BEGIN_QUOTE
This report has been produced by Guide Investimentos S.A Corretora de
Valores solely for its recipients and should not be distributed
without previous consent from Guide Investimentos S.A.  Although this
report is based upon the most reliable public information, Guide
Investimentos makes no warranties of the reliability of such
information. This document is for informational purposes only and does
not constitute any tender to sell or buy financial
instruments. Information discussed herein is not suitable for all
investors and it does not aim at providing any trading strategy for
individual goals. Investors should have experience and knowledge of
the risks in FX/Fixed Income markets. Guide Investimentos S.A
Corretora de Valores has no obligation to update, revise or modify any
information contained herein. Guide Investimentos and its analysts
shall not be held responsible for any accidental incorrect
information, nor for investment decisions taken based upon the
information contained herein. Additional information discussed on this
report is available upon request.  Analysts each certify that the
views expressed in this report represent only personal views produced
independently, including with respect Guide Investimentos S.A
Corretora de Valores. This report should not be considered as research
report ("relatório de análise") for the purposes of the article 1 of
CVM Instruction NR 483. Opinions, estimates and projections contained
herein express the current judgment of the analysts build on the date
this report was released and therefore can be changed without
notice. Analysts do not accept any liability that incorrect use of
this report could cause, including financial losses. Upon accepting
this document, one should agree with all the above-mentioned
limitations
#+END_QUOTE


* COMMENT Local Variables
# Local Variables:
# eval: (load-file "./elisp/publishing.el")
# END:
